Fix wrong path(s) on p697. Explicit log files
comorment/mixer pull request #7
Opened 2023-06-20 10:33 UTC by espenhgn

Fixes #6

2023-06-22 13:06 UTC, ofrei requested changes
I'm a bit concerned about adding
```
#SBATCH --output=MIXER_REAL.txt
#SBATCH --error=MIXER_REAL.txt
#SBATCH --open-mode=truncate
```
As users may run many MIXER jobs these files might overwrite each other.
The default SLURM file name with slurm-NNN.out where NNN is a jobID seem to be more robust - yes it's hard to find the right files, but each of them have a unique name. 

I'd be happy to modify the prefix, i.e. name MIXER_REAL-NNN.out , but then this also needs to care about job arrays, which have NNN_MMM.out format (MMM for SLURM_ARRAY_TASK_ID ).

All in all I think this is not something we need to define in the example - advanced SLURM users will change it if needed

2023-06-22 13:12 UTC, espenhgn commented
Thanks, can add that jobid to the file name (plus date-time perhaps).
Also there was some option for loading files for plotting with wildcard
matching. That'd be neater perhaps (more compact). What do you think?

tor. 22. jun. 2023, 15:06 skrev Oleksandr Frei ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> I'm a bit concerned about adding
>
> #SBATCH --output=MIXER_REAL.txt
> #SBATCH --error=MIXER_REAL.txt
> #SBATCH --open-mode=truncate
>
> As users may run many MIXER jobs these files might overwrite each other.
> The default SLURM file name with slurm-NNN.out where NNN is a jobID seem
> to be more robust - yes it's hard to find the right files, but each of them
> have a unique name.
>
> I'd be happy to modify the prefix, i.e. name MIXER_REAL-NNN.out , but then
> this also needs to care about job arrays, which have NNN_MMM.out format
> (MMM for SLURM_ARRAY_TASK_ID ).
>
> All in all I think this is not something we need to define in the example
> - advanced SLURM users will change it if needed
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/comorment/mixer/pull/7#pullrequestreview-1493148018>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AATARYL5HY52Q3X24Z5PIHTXMQ7NDANCNFSM6AAAAAAZNCLRKY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-23 08:52 UTC, espenhgn commented
Should be fixed now, including `-%A_%a` in the output file name, see https://slurm.schedmd.com/sbatch.html#OPT_output for details

2023-10-24 12:40 UTC, ofrei approved these changes

2023-10-24 12:46 UTC, merged